Add greeting controller
wolox-training/dm-java pull request #2
Opened 2020-04-21 22:06 UTC by Darvand

## Summary
- Add greeting controller

## Trello card
https://trello.com/c/Vn5BkVkW/17-crear-un-controller-y-una-vista-de-bienvenida

2020-04-22 14:51 UTC, jeymarsonwolox requested changes
Add .gitignore, this pr must be based on the `spring-boot-init` branch

2020-04-23 14:04 UTC, Jimenarosello requested changes
Just a few changes and it should be good to go 😃

2020-04-23 14:04 UTC, Jimenarosello commented on .idea/.gitignore
> +# Default ignored files
.idea and .gradle folders should be added to the gitignore 🙂

2020-04-23 14:04 UTC, Jimenarosello commented on src/main/java/wolox/training/TrainingApplication.java
> +	public static void main(String[] args) {
Please configure your IDE to use 4 spaces instead of tabs. This can be configured in the Preferences window, Code style > Java section: 

![image](https://user-images.githubusercontent.com/43755493/80107829-f9eb1600-8551-11ea-954f-fa81b5296531.png)
 
Let me know if you need any help configuring it 😄

2020-04-23 14:04 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +  public String greeting(@RequestParam(name = "name", required = false, defaultValue = "World") String name, Model model) {
Use 4 spaces instead of 2 😃

2020-04-23 17:18 UTC, jeymarsonwolox approved these changes

2020-04-26 15:04 UTC, Jimenarosello approved these changes

2020-04-27 14:15 UTC, merged