Add Book entity CRUD and REST
wolox-training/dm-java pull request #3
Opened 2020-04-23 22:09 UTC by Darvand

## Summary

- Added book entity
- Added CRUD REST for book entity

# Trello card
https://trello.com/c/rDxTxFbR/15-crear-un-repositorio-de-books
https://trello.com/c/2dpnbvBT/18-crear-las-operaciones-crud-de-book

2020-04-24 16:00 UTC, jeymarsonwolox requested changes

2020-04-24 16:00 UTC, jeymarsonwolox commented on src/main/java/wolox/training/TrainingApplication.java
> +@EntityScan("wolox.training.models")
these are not necessary

2020-04-24 16:00 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +  @Column()
`@Column` is not necessary if you don't need to specify a special feature

2020-04-24 16:00 UTC, jeymarsonwolox commented on src/main/java/wolox/training/models/Book.java
> +  public long getId() {
you can read about `Lombok` and remove setters and getters

2020-04-24 18:56 UTC, jeymarsonwolox submitted a review, later dismissed

2020-04-26 15:03 UTC, Jimenarosello requested changes
just a few comments :)

2020-04-26 15:03 UTC, Jimenarosello commented on src/main/java/wolox/training/controllers/BookController.java
> +  @Autowired
Remember to use 4 spaces instead of 2 :)

2020-04-26 15:03 UTC, Jimenarosello commented on src/main/java/wolox/training/exceptions/books/BookIdMissMatchException.java
> +}
Remember to add EOF :)

2020-04-26 15:03 UTC, Jimenarosello commented on src/main/java/wolox/training/models/Book.java
> +  }
This setter should not be included to avoid unwanted changes of the autogenerated value 🙂

2020-04-27 15:31 UTC, Jimenarosello submitted a review, later dismissed

2020-04-27 15:33 UTC, merged